// build_payloads_20260621.js — 为 20260621 批次生成 payload_template.json
const fs = require('fs');
const path = require('path');

const BATCH_DIR = 'C:/Users/31672/AI/project/wechat/文章包/20260621';

// 每篇文章的元数据 + 段落（按 --- 切分的文本块）
const articles = [
  {
    dir: '01-我们把家里的Wi-Fi分成两个',
    title: '我们把家里的Wi-Fi分成两个，吵架次数减半了',
    digest: '他外放视频到凌晨，我第二天改了路由器密码。分了网之后，他反而开始主动找我说话。',
    sections: [
      // section 1 (intro + bold heading + content)
      `<p style="margin-bottom: 1em;">那天晚上十一点，老公还瘫在沙发上刷短视频。</p><p style="margin-bottom: 1em;">声音外放。</p><p style="margin-bottom: 1em;">我喊了三遍"小点声"，他"哦"一下，过两分钟音量又爬上来。</p><p style="margin-bottom: 1em;">我没再说话，回到书房把门关上，盯着天花板躺了二十分钟。</p><p style="margin-bottom: 1em;">第二天早上，趁他还在睡，我打开路由器后台，把主Wi-Fi密码改了。</p><p style="margin-bottom: 1em;">然后新建了一个叫"Guest"的网络，密码随便给了他一个。</p><p style="margin-bottom: 1em;">他中午醒来问我："家里网怎么断了？"</p><p style="margin-bottom: 1em;">我说："改了，主网我用了，你连Guest。"</p><p style="margin-bottom: 1em;">他愣了一下："为啥？"</p><p style="margin-bottom: 1em;">"因为你声音外放，我已经忍了半年。"</p><p style="margin-bottom: 1em;">"……"</p><p style="margin-bottom: 1em;">他没说话，默默把手机切到了新网。</p><p style="margin-bottom: 1em; font-weight: bold; color: #be185d;">分了网之后，他反而开始主动找我说话了。</p><p style="margin-bottom: 1em;">一开始我以为他是在赌气，吃饭不说话，洗脸不说话，洗完澡出来也不说话。</p><p style="margin-bottom: 1em;">第三天晚上，他敲书房门："网太慢，能连一下主网吗？"</p><p style="margin-bottom: 1em;">我说不行。</p><p style="margin-bottom: 1em;">他站在门口看了我一会儿，说："那你出来坐会儿呗，外面有Wi-Fi。"</p><p style="margin-bottom: 1em;">我没忍住笑了。</p><p style="margin-bottom: 1em;">那天晚上我们坐在沙发上聊了一个多小时。</p><p style="margin-bottom: 1em;">聊的是他公司最近来了个新领导，开会爱念PPT。</p><p style="margin-bottom: 1em;">他很久没跟我说这些了。</p><p style="margin-bottom: 1em;">我也很久没问了。`,
      // section 2
      `<p style="margin-bottom: 1em;">说真的，结婚六年，我俩的关系不知道从什么时候起，变成了"同一屋檐下的两个App"。</p><p style="margin-bottom: 1em;">他刷他的，我刷我的。</p><p style="margin-bottom: 1em;">偶尔在客厅碰一下，交换一句"晚饭吃什么"。</p><p style="margin-bottom: 1em;">不算坏。</p><p style="margin-bottom: 1em;">但也谈不上好。</p><p style="margin-bottom: 1em;">我以前以为这是感情淡了，后来想明白——是边界感没了。</p><p style="margin-bottom: 1em;">不是他越界，是我俩都被"共享一切"这套默认设置困住了。</p><p style="margin-bottom: 1em;">同网、同账号、同购物车、同电视。</p><p style="margin-bottom: 1em;">你什么都一起用，最后就什么都不想说了。</p><p style="margin-bottom: 1em; font-weight: bold; color: #be185d;">分了网那天，我俩其实是默认了一件事：我们不是连体婴。</p><p style="margin-bottom: 1em;">我们是两个成年人，住在一个房子里，搭伙过日子的合伙人。</p><p style="margin-bottom: 1em;">合伙人不需要共享所有信号，只需要在关键时候能接得上。</p><p style="margin-bottom: 1em;">我想起前两年我俩因为"为什么不回我消息"大吵过一次。</p><p style="margin-bottom: 1em;">吵完发现，他在群里回了一堆客户消息，根本没看见我发的。</p><p style="margin-bottom: 1em;">那时候我委屈得不行，觉得自己在他心里排不上号。</p><p style="margin-bottom: 1em;">现在想想，他也不是不在乎，是没那么多注意力分给我。</p><p style="margin-bottom: 1em;">我也是。</p>`,
      // section 3
      `<p style="margin-bottom: 1em;">分网第三周，他主动提了个事。</p><p style="margin-bottom: 1em;">"要不咱俩把账号也分一下？"</p><p style="margin-bottom: 1em;">我说："你啥账号？"</p><p style="margin-bottom: 1em;">"购物车的。"</p><p style="margin-bottom: 1em;">我笑出声。</p><p style="margin-bottom: 1em;">他认真说："每次我加进购物车的东西都被你默默删掉，挺烦的。"</p><p style="margin-bottom: 1em;">我："……你不也知道我删了。"</p><p style="margin-bottom: 1em;">"知道，但我没说。"</p><p style="margin-bottom: 1em;">那天我们花了一晚上把购物车拆了。</p><p style="margin-bottom: 1em;">各买各的，最后结账各自付。</p><p style="margin-bottom: 1em;">听起来挺矫情。</p><p style="margin-bottom: 1em;">但我俩那晚情绪都松了。</p><p style="margin-bottom: 1em;">朋友问我："你们这算分居吗？"</p><p style="margin-bottom: 1em;">我说不算，我们还在一张床上睡，还一起做饭，还一起遛狗。</p><p style="margin-bottom: 1em;">只是各自有自己的一片网，各自有自己的一份购物车。</p><p style="margin-bottom: 1em;">朋友："那不就是室友？"</p><p style="margin-bottom: 1em;">我想了想，可能就是。</p><p style="margin-bottom: 1em;">但说真的，中年婚姻走到这一步，能当个相处舒服的室友，已经比很多夫妻强了。</p><p style="margin-bottom: 1em;">我不再期待他懂我每一个深夜的小情绪。</p><p style="margin-bottom: 1em;">他也不要求我陪他看每一集他不喜欢的剧。</p><p style="margin-bottom: 1em;">我们各自有自己的小屏幕，然后在客厅、在饭桌、在遛狗的路上，碰一下。</p><p style="margin-bottom: 1em;">碰上就聊几句，碰不上就各过各的。</p><p style="margin-bottom: 1em;">不累。</p>`,
      // section 4 (final, no image after)
      `<p style="margin-bottom: 1em;">前两天他突然在客厅喊我："主网能给我用一下吗？我下个东西。"</p><p style="margin-bottom: 1em;">我走出去，看他蹲在路由器旁边，手机举得老高。</p><p style="margin-bottom: 1em;">"密码多少来着？"</p><p style="margin-bottom: 1em;">我没告诉他，蹲下来把手机接过，自己输进去。</p><p style="margin-bottom: 1em;">他凑过来看了一眼："你都不让我记住密码。"</p><p style="margin-bottom: 1em;">"嗯。"</p><p style="margin-bottom: 1em;">"那我以后每次想用都得求你？"</p><p style="margin-bottom: 1em;">"对。"</p><p style="margin-bottom: 1em;">他乐了。</p><p style="margin-bottom: 1em;">我也乐了。</p><p style="margin-bottom: 1em;">厨房水壶开了，他先起身去关火，回头说："你那个Guest网，真的好慢。"</p><p style="margin-bottom: 1em;">"慢就对了。"</p><p style="margin-bottom: 1em;">窗外天快黑了，他打开主网连上的手机，递给我看一个视频。</p><p style="margin-bottom: 1em;">是一段搞笑的猫。</p><p style="margin-bottom: 1em;">我们俩在路由器旁边蹲着笑了很久。</p><p style="margin-bottom: 1em;">咖啡凉了。</p><p style="margin-bottom: 1em;">我合上电脑，把杯子拿去洗了。</p><p style="margin-top: 2em; margin-bottom: 1em; color: #888; font-size: 14px;">写了三个小时，给个「在看」吧。如果你也想过把家里的Wi-Fi分一下，转给那个也需要的人。</p>`,
    ],
  },
  {
    dir: '02-同事辞职开了家代吵架工作室',
    title: '同事辞职去开了家"代吵架"工作室，月入三万',
    digest: '老周发朋友圈"代吵架，300一次"。我以为他开玩笑，直到他给我发消息借200。',
    sections: [
      `<p style="margin-bottom: 1em;">上个月刷朋友圈，看到老周发了条状态——</p><p style="margin-bottom: 1em;">"代吵架，300一次。远程500。"</p><p style="margin-bottom: 1em;">下面评论一水的"哈哈哈"，没人当真。</p><p style="margin-bottom: 1em;">我也"哈哈"了一下，划过去了。</p><p style="margin-bottom: 1em;">直到上周他给我发消息："在吗？借我200。"</p><p style="margin-bottom: 1em;">我以为是诈骗号，视频过去确认了一下，确实是本人。</p><p style="margin-bottom: 1em;">他这才告诉我——他真辞职了，开了一家"代吵架"工作室，专门替人吵。</p><p style="margin-bottom: 1em;">"工作室"听起来很厉害，其实是他租的一个15平的小办公室，一张桌子、一台电脑、两部手机。</p><p style="margin-bottom: 1em;">他管这叫"情绪服务商"。</p><p style="margin-bottom: 1em;">我笑出来。</p>`,
      `<p style="margin-bottom: 1em;">老周原来跟我同一个组，写了五年代码，去年还在卷KPI。</p><p style="margin-bottom: 1em;">被裁那天他没骂公司，发了条朋友圈："终于不用周末偷偷摸摸打游戏了。"</p><p style="margin-bottom: 1em;">我们以为他缓一缓就重新找工作。</p><p style="margin-bottom: 1em;">结果他缓着缓着，开了这家工作室。</p><p style="margin-bottom: 1em;">我问他："接的第一单是什么？"</p><p style="margin-bottom: 1em;">他说是替一个妈妈跟学校吵架。</p><p style="margin-bottom: 1em;">学校不让孩子午休，理由是"统一管理"。妈妈去理论被怼回来，气得在车里哭。</p><p style="margin-bottom: 1em;">老周接单后，先打了一通电话，被挂了。</p><p style="margin-bottom: 1em;">他换了个手机号，又打。</p><p style="margin-bottom: 1em;">对方不耐烦："你谁啊？"</p><p style="margin-bottom: 1em;">"我是孩子家属。"</p><p style="margin-bottom: 1em;">"哪个孩子的？"</p><p style="margin-bottom: 1em;">"你别管哪个孩子，我就问一句——午休这事儿违反哪条规定？"</p><p style="margin-bottom: 1em;">对方："……"</p><p style="margin-bottom: 1em;">老周后来跟我说，他发现一件很有意思的事——大部分人不会吵架。</p><p style="margin-bottom: 1em;">一吵架就哭，一哭就词穷，最后变成情绪发泄，事情没解决。</p><p style="margin-bottom: 1em;">他做的事说白了就是替客户把"情绪"和"诉求"分开。</p>`,
      `<p style="margin-bottom: 1em;">"这玩意儿有人付钱？"我问他。</p><p style="margin-bottom: 1em;">"多得很。"</p><p style="margin-bottom: 1em;">他说他接过的客户里，有跟物业吵架的、跟物业吵架的邻居、跟前任要抚养费的、跟房东退押金的、跟公司HR谈赔偿的。</p><p style="margin-bottom: 1em;">300到500一单，远程500到800。</p><p style="margin-bottom: 1em;">复杂点的，比如跨城跟开发商扯皮，1000起。</p><p style="margin-bottom: 1em;">月入三万，他自己都没料到。</p><p style="margin-bottom: 1em;">"我以为这是个临时生意，结果发现大家都累到没力气吵了。"</p><p style="margin-bottom: 1em;">我听到这句话愣了一下。</p><p style="margin-bottom: 1em;">老周说的"大家都累到没力气吵"——这话我太有感觉了。</p><p style="margin-bottom: 1em;">我自己就是。</p><p style="margin-bottom: 1em;">去年房东不退我两千押金，理由是"墙上有钉子眼"。</p><p style="margin-bottom: 1em;">我知道那是装修时候打的，不是我弄的。</p><p style="margin-bottom: 1em;">但我连跟房东理论三句话的力气都没。</p><p style="margin-bottom: 1em;">我发了条消息过去，对方回得阴阳怪气，我直接关了聊天框，自认倒霉。</p><p style="margin-bottom: 1em;">两千块就这么没了。</p><p style="margin-bottom: 1em;">我那时候想——要是有个人能替我吵，我付五百都愿意。</p><p style="margin-bottom: 1em;">省心。</p><p style="margin-bottom: 1em;">省情绪。</p><p style="margin-bottom: 1em;">省我自己崩溃一整晚。</p>`,
      `<p style="margin-bottom: 1em;">老周说他接单有原则。</p><p style="margin-bottom: 1em;">不接涉及暴力的，不接诽谤造谣的，不接家庭内部矛盾里"替一方怼另一方"的。</p><p style="margin-bottom: 1em;">"家庭的我一律拒。"</p><p style="margin-bottom: 1em;">"为啥？"</p><p style="margin-bottom: 1em;">"人家夫妻吵完会和好，我成外人了。"</p><p style="margin-bottom: 1em;">我笑出声，但又觉得他这话有点暖。</p><p style="margin-bottom: 1em;">他还说，他不太喜欢接那种"无理取闹"的单。</p><p style="margin-bottom: 1em;">"有的客户就是想出口气，没道理我帮不了。"</p><p style="margin-bottom: 1em;">"那你怎么判断有没有道理？"</p><p style="margin-bottom: 1em;">"听完故事我自己判断。我没理的单我也退。"</p><p style="margin-bottom: 1em;">我看着他，挺意外的。</p><p style="margin-bottom: 1em;">写代码那会儿他是个闷葫芦，跟人沟通能躲就躲。</p><p style="margin-bottom: 1em;">现在反而不一样了。</p><p style="margin-bottom: 1em;">我问老周："你不觉得这工作……不体面吗？"</p><p style="margin-bottom: 1em;">他盯着我看了两秒，笑了一下。</p><p style="margin-bottom: 1em;">"以前在公司加班到凌晨两点改PPT，第二天开会被领导怼，我都没觉得体面。"</p><p style="margin-bottom: 1em;">"现在替人吵一架，吵完对方服软，客户高兴，我也拿到钱。"</p><p style="margin-bottom: 1em;">"我觉得这才叫体面。"</p><p style="margin-bottom: 1em;">他说他现在睡得着了。</p><p style="margin-bottom: 1em;">以前半夜起来看消息提醒，心跳都会加速。</p><p style="margin-bottom: 1em;">现在手机半夜响，他反而清醒——又来活了。</p><p style="margin-bottom: 1em;">前天他给我发了一张工作室的照片。</p><p style="margin-bottom: 1em;">桌子很小，电脑很旧，墙上贴了一张便利贴。</p><p style="margin-bottom: 1em;">便利贴上写的是他自己的座右铭——</p><p style="margin-bottom: 1em;">"别真生气。"</p><p style="margin-bottom: 1em;">我看了很久，没回。</p><p style="margin-bottom: 1em;">也可能——我自己的工作，没我想的那么不可替代。</p><p style="margin-bottom: 1em;">这件事过去快一周了，我现在想起来还是会笑。</p><p style="margin-top: 2em; margin-bottom: 1em; color: #888; font-size: 14px;">如果你身边也有一个累到不会吵架的人，转给他。让他知道，不擅长的事，可以请人代劳。</p>`,
    ],
  },
  {
    dir: '03-我开始记录今天没做什么',
    title: '我开始记录"今天没做什么"，焦虑减了一半',
    digest: '那天打开待办App看到20条未完成，我关掉了。第二天我开了一个新备忘录，叫"今天没做什么"。',
    sections: [
      `<p style="margin-bottom: 1em;">上个月某天晚上，我打开待办App，看到20条未完成事项。</p><p style="margin-bottom: 1em;">我盯着屏幕看了三秒，第一反应是——关掉。</p><p style="margin-bottom: 1em;">不是没动力。</p><p style="margin-bottom: 1em;">是看着那20条，我感觉自己整个人都被压在一座看不见的山下面。</p><p style="margin-bottom: 1em;">第二天早上醒来，我做了一个反向实验。</p><p style="margin-bottom: 1em;">我开了一个新备忘录，标题叫"今天没做什么"。</p><p style="margin-bottom: 1em;">然后我写下了第一条：</p><p style="margin-bottom: 1em;">"今天没回老板那条催进度的消息。"</p><p style="margin-bottom: 1em;">写完我发现，整个人松了一点。</p>`,
      `<p style="margin-bottom: 1em;">接下来一个月，我每天晚上写一份"没做什么"清单。</p><p style="margin-bottom: 1em;">有时候长，有时候短。</p><p style="margin-bottom: 1em;">短的时候是：</p><p style="margin-bottom: 1em;">"今天没加班。"</p><p style="margin-bottom: 1em;">"今天没刷短视频到凌晨。"</p><p style="margin-bottom: 1em;">"今天没跟同事比谁的周报更长。"</p><p style="margin-bottom: 1em;">长的时候是：</p><p style="margin-bottom: 1em;">"今天没回那个不太熟的同行的好友申请。"</p><p style="margin-bottom: 1em;">"今天没回复群里那条阴阳怪气的艾特。"</p><p style="margin-bottom: 1em;">"今天没逼自己去健身房，回家躺了一小时。"</p><p style="margin-bottom: 1em;">"今天没在脑子里反复回放昨天那个尴尬瞬间。"</p><p style="margin-bottom: 1em;">写完之后我会念一遍。</p><p style="margin-bottom: 1em;">念完会笑。</p><p style="margin-bottom: 1em;">——原来我今天居然"没做"这么多事。</p>`,
      `<p style="margin-bottom: 1em;">不知道从什么时候开始，我们都活在一种"待办焦虑"里。</p><p style="margin-bottom: 1em;">起床第一件事是看消息。</p><p style="margin-bottom: 1em;">睡觉前最后一件事是确认明天的日程。</p><p style="margin-bottom: 1em;">朋友圈里全是"今日复盘""读书打卡""健身100天"。</p><p style="margin-bottom: 1em;">像每个人都在跑一场看不见终点的马拉松，谁都不肯停下来。</p><p style="margin-bottom: 1em;">我自己以前就是典型。</p><p style="margin-bottom: 1em;">我有一份"年度目标清单"，每年1月1日更新。</p><p style="margin-bottom: 1em;">每年12月31日翻出来骂自己一次。</p><p style="margin-bottom: 1em;">坚持了五年。</p><p style="margin-bottom: 1em;">今年没坚持。</p><p style="margin-bottom: 1em;">不是因为我懒。</p><p style="margin-bottom: 1em;">是我突然意识到——我所有的"目标"，都是别人告诉我应该有的目标。</p><p style="margin-bottom: 1em;">早起、读书、健身、副业、学英语。</p><p style="margin-bottom: 1em;">这些事本身没错。</p><p style="margin-bottom: 1em;">但叠在一起，就成了一个"我必须成为更好版本的自己"的KPI。</p><p style="margin-bottom: 1em;">而这KPI，没人给我打分，也没人付我钱。</p><p style="margin-bottom: 1em;">是我自己给自己加的。</p>`,
      `<p style="margin-bottom: 1em;">记录"没做什么"之后，最大的变化是——</p><p style="margin-bottom: 1em;">我开始允许自己"不做"。</p><p style="margin-bottom: 1em;">以前周末躺一上午，我心里是慌的。</p><p style="margin-bottom: 1em;">"该出去运动了。""该写那篇文章了。""该回那个邮件了。"</p><p style="margin-bottom: 1em;">现在周末躺一上午，我会在备忘录里写一句：</p><p style="margin-bottom: 1em;">"今天上午没做任何有用的事，看了三集剧。"</p><p style="margin-bottom: 1em;">写完心里就踏实了。</p><p style="margin-bottom: 1em;">像把这笔账记下来了——不是没做，是主动选择不做。</p><p style="margin-bottom: 1em;">我有个朋友问过我："那你不会更废吗？"</p><p style="margin-bottom: 1em;">我说不会。</p><p style="margin-bottom: 1em;">因为我"主动不做"之后，反而更想做点事了。</p><p style="margin-bottom: 1em;">周六躺了一上午之后，我下午会主动出去散步。</p><p style="margin-bottom: 1em;">周日完全放空一天之后，周一开会我能更专注。</p><p style="margin-bottom: 1em;">以前我周日下午就开始焦虑——因为周一要上班。</p><p style="margin-bottom: 1em;">现在不会。</p><p style="margin-bottom: 1em;">因为我已经把"周日下午用来什么都不干"写进了清单。</p><p style="margin-bottom: 1em;">它成了一件"完成的事"。</p><p style="margin-bottom: 1em;">说真的，这事儿我跟我妈说过一次。</p><p style="margin-bottom: 1em;">我妈："你这不是给自己找借口偷懒吗？"</p><p style="margin-bottom: 1em;">我说："妈，你退休后每天打麻将，那算偷懒吗？"</p><p style="margin-bottom: 1em;">我妈："那不一样。"</p><p style="margin-bottom: 1em;">"哪不一样？"</p><p style="margin-bottom: 1em;">"我老了。"</p><p style="margin-bottom: 1em;">我笑了半天。</p><p style="margin-bottom: 1em;">也对。</p><p style="margin-bottom: 1em;">我们这一代，30岁就开始给自己定"养老KPI"了。</p><p style="margin-bottom: 1em;">健身、抗衰、读书、冥想。</p><p style="margin-bottom: 1em;">全都为了"老得慢一点"。</p><p style="margin-bottom: 1em;">但你细想——这些事越多，我们越不自由。</p><p style="margin-bottom: 1em;">不是这些事不好。</p><p style="margin-bottom: 1em;">是我们把它们变成了"必须"。</p><p style="margin-bottom: 1em;">而"必须"会反噬一切快乐。</p><p style="margin-bottom: 1em;">这一个月下来，我睡眠好了。</p><p style="margin-bottom: 1em;">以前12点躺下，1点还在脑子里列明天的待办。</p><p style="margin-bottom: 1em;">现在12点躺下，脑子里念一遍"今天没做什么"，10分钟入睡。</p><p style="margin-bottom: 1em;">我跟我那个一直失眠的同事推荐了这个方法。</p><p style="margin-bottom: 1em;">她试了一周跟我说："诶，真的好使。"</p><p style="margin-bottom: 1em;">"为啥？"</p><p style="margin-bottom: 1em;">"因为写完之后我发现——我今天其实什么都没做。"</p><p style="margin-bottom: 1em;">"……"</p><p style="margin-bottom: 1em;">"那不就证明了我没做的那些事，根本不重要吗？"</p><p style="margin-bottom: 1em;">我愣了一下。</p><p style="margin-bottom: 1em;">她说得对。</p><p style="margin-bottom: 1em;">很多时候我们焦虑的不是"做了多少"，而是"还没做的那一堆"。</p><p style="margin-bottom: 1em;">而那一堆里，80%不做也没人会发现。</p><p style="margin-bottom: 1em;">我还在记。</p><p style="margin-bottom: 1em;">每天晚上一条"今天没做什么"。</p><p style="margin-bottom: 1em;">有时候短得就一句"今天没逼自己"。</p><p style="margin-bottom: 1em;">有时候长一点。</p><p style="margin-bottom: 1em;">不管长短，写完我都觉得自己过了完整的一天。</p><p style="margin-bottom: 1em;">不是高效的完整。</p><p style="margin-bottom: 1em;">是"我自己选择的"完整。</p><p style="margin-bottom: 1em;">你呢，你今天有没有什么"没做"的事，值得记下来？</p><p style="margin-top: 2em; margin-bottom: 1em; color: #888; font-size: 14px;">如果你也常常对着未完成清单喘不过气，点个「在看」，让我知道你也在试着放过自己。</p>`,
    ],
  },
  {
    dir: '04-00后整顿职场三年后',
    title: '00后整顿职场三年后，他们也开始"安静辞职"了',
    digest: '去年公司来了个00后，第二周在群里怼了领导。我以为他活不过试用期。结果他活过了。',
    sections: [
      `<p style="margin-bottom: 1em;">去年公司来了个00后，叫小林。</p><p style="margin-bottom: 1em;">入职第二周，他在公司群里怼了一次领导。</p><p style="margin-bottom: 1em;">领导发了一长段"关于本周复盘的几点思考"，小林回："总结一下就是让我们加班。"</p><p style="margin-bottom: 1em;">群里没人接话。</p><p style="margin-bottom: 1em;">我截图发给朋友："这小孩怕是活不过试用期。"</p><p style="margin-bottom: 1em;">结果他活过了。</p><p style="margin-bottom: 1em;">还成了我们部门那个季度最受欢迎的人。</p><p style="margin-bottom: 1em;">我们都偷偷羡慕他敢说我们不敢说的话。</p>`,
      `<p style="margin-bottom: 1em;">今年三月份，小林换了个头像。</p><p style="margin-bottom: 1em;">原来是一张怼脸自拍，新头换成了一张风景图。</p><p style="margin-bottom: 1em;">山，云，没什么人。</p><p style="margin-bottom: 1em;">我当时没多想。</p><p style="margin-bottom: 1em;">后来慢慢发现——他不太在群里说话了。</p><p style="margin-bottom: 1em;">开会的时候，他坐在最后一排，专心记笔记。</p><p style="margin-bottom: 1em;">领导说什么他都"嗯""好的""收到"。</p><p style="margin-bottom: 1em;">我以为他这是被打磨了，准备提离职。</p><p style="margin-bottom: 1em;">结果没有。</p><p style="margin-bottom: 1em;">他一直留着，安安静静地按时上下班。</p><p style="margin-bottom: 1em;">从不主动加班。</p><p style="margin-bottom: 1em;">从不主动接不属于自己范围的事。</p><p style="margin-bottom: 1em;">从不主动给同事发"加油"表情包。</p><p style="margin-bottom: 1em;">但他负责的事，从没出过岔子。</p><p style="margin-bottom: 1em;">我突然意识到——他不是被磨平了。</p><p style="margin-bottom: 1em;">他是换了个打法。</p>`,
      `<p style="margin-bottom: 1em;">我以前以为，"00后整顿职场"是个爽文叙事。</p><p style="margin-bottom: 1em;">年轻人来了，怼老板、准点下班、拒绝团建、要双休、要远程、要情绪价值。</p><p style="margin-bottom: 1em;">老板们一开始慌。</p><p style="margin-bottom: 1em;">三年过去，老板们不慌了。</p><p style="margin-bottom: 1em;">因为老板们发现——00后这一茬，火气来得快，去得也快。</p><p style="margin-bottom: 1em;">怼完一通发现工资没涨、加班没减、KPI没变。</p><p style="margin-bottom: 1em;">吵赢了又怎样？</p><p style="margin-bottom: 1em;">该开的会还得开。</p><p style="margin-bottom: 1em;">该写的周报还得写。</p><p style="margin-bottom: 1em;">该背的锅还得背。</p><p style="margin-bottom: 1em;">小林有次跟我说过一句话，我记到现在。</p><p style="margin-bottom: 1em;">"哥，我跟领导吵了一年，最后发现吵架的成本是我自己付的。"</p><p style="margin-bottom: 1em;">"领导该下班下班，我吵完一肚子气睡不着。"</p><p style="margin-bottom: 1em;">"后来想明白了——我不用跟他吵，我跟他耗。"</p>`,
      `<p style="margin-bottom: 1em;">"耗"这个词，让我心里咯噔一下。</p><p style="margin-bottom: 1em;">我工作了十年，最近两年才隐约摸到这个门道。</p><p style="margin-bottom: 1em;">而小林23岁就摸到了。</p><p style="margin-bottom: 1em;">他说他的策略很简单：</p><p style="margin-bottom: 1em;">把工作当合同。</p><p style="margin-bottom: 1em;">合同里写的就做，没写的不做。</p><p style="margin-bottom: 1em;">不内卷，也不抱怨。</p><p style="margin-bottom: 1em;">不投入感情，也不敌视公司。</p><p style="margin-bottom: 1em;">老板说什么就说什么。</p><p style="margin-bottom: 1em;">该完成的事情完成，该下班的时间下班。</p><p style="margin-bottom: 1em;">不主动学习"超出本岗位的技能"，因为那是免费给公司打工。</p><p style="margin-bottom: 1em;">不参加"自愿团建"，因为自愿就是强迫。</p><p style="margin-bottom: 1em;">不回复工作群里非工作时间发的消息，除非真出了大事。</p><p style="margin-bottom: 1em;">我问他："这样不会被裁吗？"</p><p style="margin-bottom: 1em;">他说："会，但被裁了我也无所谓。"</p><p style="margin-bottom: 1em;">"为什么？"</p><p style="margin-bottom: 1em;">"我又没把命压在这。"</p><p style="margin-bottom: 1em;">我听完沉默了很久。</p><p style="margin-bottom: 1em;">我自己呢？</p><p style="margin-bottom: 1em;">我这十年，把所有情绪都押在工作上了。</p><p style="margin-bottom: 1em;">老板夸我一句，我能开心三天。</p><p style="margin-bottom: 1em;">老板皱个眉，我能复盘一周。</p><p style="margin-bottom: 1em;">我把工作当成了"我自己"。</p><p style="margin-bottom: 1em;">所以我特别累。</p><p style="margin-bottom: 1em;">小林不是。</p><p style="margin-bottom: 1em;">他把工作当一份合同，签了字，按条款办事，到期走人。</p><p style="margin-bottom: 1em;">他不打算在这里实现什么自我价值。</p><p style="margin-bottom: 1em;">他的自我价值在别处——下班之后打游戏、跟朋友吃饭、看直播、攒钱去旅游。</p><p style="margin-bottom: 1em;">他跟我说他攒了三万块，准备今年年底去趟云南。</p><p style="margin-bottom: 1em;">"工作不是用来攒人生经历的，工作就是用来换钱的。"</p><p style="margin-bottom: 1em;">我听完，挺受冲击。</p><p style="margin-bottom: 1em;">前两天，小林递了辞呈。</p><p style="margin-bottom: 1em;">我没问他去哪。</p><p style="margin-bottom: 1em;">他也没在朋友圈发"要离开这个糟糕的地方"之类的话。</p><p style="margin-bottom: 1em;">他临走那天跟我吃了顿饭。</p><p style="margin-bottom: 1em;">他说："哥，你以后少加点班。"</p><p style="margin-bottom: 1em;">"为啥？"</p><p style="margin-bottom: 1em;">"我看你黑眼圈一年比一年重。"</p><p style="margin-bottom: 1em;">"……我习惯。"</p><p style="margin-bottom: 1em;">"习惯也得改。"</p><p style="margin-bottom: 1em;">吃完饭我送他到地铁站。</p><p style="margin-bottom: 1em;">地铁口他回头摆了摆手："云南回来给你带花。"</p><p style="margin-bottom: 1em;">"什么花？"</p><p style="margin-bottom: 1em;">"不知道，看到合适的买。"</p><p style="margin-bottom: 1em;">然后他转身进站。</p><p style="margin-bottom: 1em;">地铁口人很多，他很快就被淹没了。</p><p style="margin-bottom: 1em;">我站在原地站了一会儿。</p><p style="margin-bottom: 1em;">风挺大的。</p><p style="margin-bottom: 1em;">后来我又路过公司楼下那家面馆，灯还亮着。但小林不在那个店里吃面了。</p><p style="margin-top: 2em; margin-bottom: 1em; color: #888; font-size: 14px;">如果你也在"用力过猛"和"安静辞职"之间摇摆，点个「在看」。让你我都知道，换一种活法，没那么难。</p>`,
    ],
  },
];

// 构建 HTML：每段用 section 包裹，section 之间插 {{IMGx}}
const STYLE = 'padding: 0 16px; font-size: 15px; color: #4a4a4a; letter-spacing: 0.5px; line-height: 1.75;';

for (const art of articles) {
  const htmlParts = [];
  for (let i = 0; i < art.sections.length; i++) {
    htmlParts.push(`<section style="${STYLE}">${art.sections[i]}</section>`);
    // 前3个 section 后插入图片占位符（对应 img1, img2, img3）
    if (i < 3) {
      htmlParts.push(`<p style="text-align: center; margin: 1.5em 0;"><img src="{{IMG${i}}}" style="max-width: 100%;" /></p>`);
    }
  }
  const content = htmlParts.join('\n');
  const payload = {
    articles: [{
      title: art.title,
      author: '',
      digest: art.digest,
      content,
      content_source_url: '',
      thumb_media_id: '{{THUMB}}',
      need_open_comment: 1,
      only_fans_can_comment: 0,
    }],
  };
  const outPath = path.join(BATCH_DIR, art.dir, 'payload_template.json');
  fs.writeFileSync(outPath, JSON.stringify(payload, null, 2));
  console.log(`✅ ${art.dir}/payload_template.json`);
}

console.log('\n全部完成');
